# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

require 'sunlight'

pols = Sunlight::Legislator.all_where(in_office: 'true')

pols.each do |pol|
    hash = {title: pol.title,
            firstname: pol.firstname,
            nickname: pol.nickname,
            last_name: pol.lastname,
            name_suffix: pol.name_suffix,
            party: pol.party,
            state: pol.state,
            district: pol.district,
            in_office: pol.in_office,
            gender: pol.gender,
            birthdate: pol.birthdate,
            senate_class: pol.senate_class,
            bioguide_id: pol.bioguide_id,
            votesmart_id: pol.votesmart_id,
            govtrack_id: pol.govtrack_id,
            crp_id: pol.crp_id}
      Politician.create(hash)
end

searches = [{name: "Search",                                    category: "Entity Search"},
            {name: "Find Politician",                           category: "Entity Search"},
            {name: "Find Individual",                           category: "Entity Search"},
            {name: "Find Organization",                         category: "Entity Search"},
            {name: "Find Industry",                             category: "Entity Search"},
            {name: "Overview",                                  category: "Entity Search"},
            {name: "Individual Contributions Given",            category: "Individual"},
            {name: "Top Recipient Organizations",               category: "Individual"},
            {name: "Top Recipient Politicians",                 category: "Individual"},
            {name: "Party Breakdown",                           category: "Individual"},
            {name: "Lobbying Registrants",                      category: "Individual"},
            {name: "Lobbying Clients",                          category: "Individual"},
            {name: "Lobbying Issues",                           category: "Individual"},
            {name: "Top Industries",                            category: "Industry"},
            {name: "Top Organizations",                         category: "Industry"},
            {name: "Campaign Contributions",                    category: "Itemized Search"},
            {name: "Bundled Campaign Contributions",            category: "Itemized Search"},
            {name: "Contractor Misconduct",                     category: "Itemized Search"},
            {name: "Earmarks",                                  category: "Itemized Search"},
            {name: "EPA ECHO",                                  category: "Itemized Search"},
            {name: "FACA Memberships",                          category: "Itemized Search"},
            {name: "Federal Contracts",                         category: "Itemized Search"},
            {name: "Federal Grants",                            category: "Itemized Search"},
            {name: "Lobbying Registrations",                    category: "Itemized Search"},
            {name: "Top Organizations by Contributions Given",  category: "Organization"},
            {name: "Top Recipients",                            category: "Organization"},
            {name: "Party Breakdown",                           category: "Organization"},
            {name: "State/Federal Breakdown",                   category: "Organization"},
            {name: "Lobbying Registrants",                      category: "Organization"},
            {name: "Lobbying Issues",                           category: "Organization"},
            {name: "Bills",                                     category: "Organization"},
            {name: "Lobbyists",                                 category: "Organization"},
            {name: "Registrant Clients",                        category: "Organization"},
            {name: "Registrant Issues",                         category: "Organization"},
            {name: "Registrant Bills",                          category: "Organization"},
            {name: "Registrant Lobbyists",                      category: "Organization"},
            {name: "Mentions in Regulations",                   category: "Organization"},
            {name: "Regulatory Submissions",                    category: "Organization"},
            {name: "FACA Memberships",                          category: "Organization"},
            {name: "FEC Summary",                               category: "Organization"},
            {name: "FEC Summary",                               category: "Organization"},
            {name: "Top Politicians by Contributions Received", category: "Politician"},
            {name: "Top Contributors",                          category: "Politician"},
            {name: "Top Industries",                            category: "Politician"},
            {name: "Top Sectors",                               category: "Politician"},
            {name: "Local Breakdowns",                          category: "Politician"},
            {name: "Contributor Type Breakdown",                category: "Politician"},
            {name: "FEC Independent Expenditures",              category: "Politician"},
            {name: "Unknown Industries",                        category: "Politician"},
            {name: "Top Sectors",                               category: "Politician"}
          ]

searches.each do |search|
   search_hash = {name: search[:name], category: search[:category]}
   Search.create(search_hash)
end


search_params = [{name: "Search",                     parameter:"search",                   kind:"string",                      category: "Entity Lookups",              method: "Search by Name"},
                 {name: "Type",                       parameter:"type",                     kind:"enumerated",                  category: "Entity Lookups",              method: "Search by Name"},
                 {name: "Namespace",                  parameter:"namespace",                kind:"enumerated",                  category: "Entity Lookups",              method: "ID Lookup"},
                 {name: "ID",                         parameter:"id",                       kind:"string",                      category: "Entity Lookups",              method: "ID Lookup"},
                 {name: "Bioguide ID",                parameter:"bioguide_id",              kind:"string",                      category: "Entity Lookups",              method: "ID Lookup"},
                 {name: "Election Cycle",             parameter:"cycle",                    kind:"string",                      category: "Entity Lookups",              method: "Entity Overview"},
                 {name: "Entity ID" ,                 parameter:"entity_id",                kind:"string",                      category: "Entity Lookups",              method: "Entity Overview"},
                 {name: "Amount",                     parameter:"amount",                   kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Contributor Name",           parameter:"contributor_ft",           kind:"string",                      category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Contributor State",          parameter:"contributor_state",        kind:"string",                      category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Date",                       parameter:"date",                     kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "For or Against",             parameter:"for_against",              kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Organization Name",          parameter:"organization_ft",          kind:"string",                      category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Recipient State",            parameter:"recipient_state",          kind:"string",                      category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Seat",                       parameter:"seat",                     kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Transaction Type",           parameter:"transaction_namespace",    kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Campaign Contributions"},
                 {name: "Lobbyist Name",              parameter:"lobbyist_name",            kind:"string",                      category: "Search Methods (Itemized)",   method:"Bundled Campaign Contributions"},
                 {name: "Recipient Name",             parameter:"recipient_name",           kind:"string",                      category: "Search Methods (Itemized)",   method:"Bundled Campaign Contributions"},
                 {name: "Contractor Name",            parameter:"contractor",               kind:"string",                      category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Contracting Party",          parameter:"contracting_party",        kind:"string",                      category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Year",                       parameter:"date_year",                kind:"string",                      category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Enforcement Agency",         parameter:"enforcement_agency",       kind:"string",                      category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Instance Description",       parameter:"instance",                 kind:"string",                      category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Penalty Amount",             parameter:"penalty_amount",           kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Contractor Misconduct"},
                 {name: "Bill",                       parameter:"bill",                     kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Amount",                     parameter:"amount",                   kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "City",                       parameter:"city",                     kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Description",                parameter:"description",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Member of Congress",         parameter:"member",                   kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Member Party",               parameter:"member_party",             kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Member State",               parameter:"member_state",             kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Recipient",                  parameter:"recipient",                kind:"string",                      category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Year",                       parameter:"year",                     kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"Earmarks"},
                 {name: "Case Name",                  parameter:"case_name",                kind:"string",                      category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Case Number",                parameter:"case_num",                 kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Defendants",                 parameter:"defendants",               kind:"string",                      category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Start Date",                 parameter:"first_date",               kind:"date",                        category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "End Date",                   parameter:"last_date",                kind:"date",                        category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Location Addresses",         parameter:"location_addresses",       kind:"string",                      category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Penalty",                    parameter:"penalty",                  kind:"comparison",                  category: "Search Methods (Itemized)",   method:"EPA Echo"},
                 {name: "Affiliation",                parameter:"affiliation",              kind:"string",                      category: "Search Methods (Itemized)",   method:"FACA Memberships"},
                 {name: "Agency Name",                parameter:"agency_name",              kind:"string",                      category: "Search Methods (Itemized)",   method:"FACA Memberships"},
                 {name: "Comittee Name",              parameter:"comittee_name",            kind:"string",                      category: "Search Methods (Itemized)",   method:"FACA Memberships"},
                 {name: "Member Name",                parameter:"member_name",              kind:"string",                      category: "Search Methods (Itemized)",   method:"FACA Memberships"},
                 {name: "Year",                       parameter:"year",                     kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"FACA Memberships"},
                 {name: "Agency ID",                  parameter:"agency_id",                kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Contracting Agency ID",      parameter:"contracting_agency_id",    kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Current Amount",             parameter:"current_amount",           kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Fiscal Year",                parameter:"fiscal_year",              kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Maximum Amount",             parameter:"maximum_amount",           kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Obligated Amount",           parameter:"obligated_amount",         kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Congressional District",     parameter:"place_district",           kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "State",                      parameter:"place_state",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Requesting Agency ID",       parameter:"requesting_agency_id",     kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Signed Date",                parameter:"signed_date",              kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor City",                parameter:"vendor_city",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor District",            parameter:"vendor_district",          kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor DUNS ID",             parameter:"vendor_duns",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor Name",                parameter:"vendor_name",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor Parent DUNS ID",      parameter:"vendor_parent_duns",       kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor State",               parameter:"vendor_state",             kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Vendor Zip Code",            parameter:"vendor_zipcode",           kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Contracts"},
                 {name: "Agency Name",                parameter:"agency_ft",                kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Total Amount",               parameter:"amount_total",             kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Type of Assistance",         parameter:"assistance_type",          kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Fiscal Year",                parameter:"fiscal_year",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Recipient Name",             parameter:"recipient_ft",             kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Recipient State",            parameter:"recipient_state",          kind:"string",                      category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Recipient Type",             parameter:"recipient_type",           kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Federal Grants"},
                 {name: "Amount",                     parameter:"amount",                   kind:"comparison",                  category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Client",                     parameter:"client_ft",                kind:"string",                      category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Client Parent Organization", parameter:"client_parent_ft",         kind:"string",                      category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Filing Type",                parameter:"filing_type",              kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Lobbyist Name",              parameter:"lobbyist_ft",              kind:"string",                      category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Registrant",                 parameter:"registrant_ft",            kind:"string",                      category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Transaction ID",             parameter:"transaction_id",           kind:"string",                      category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Transaction Type",           parameter:"transaction_type",         kind:"enumerated",                  category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Year",                       parameter:"year",                     kind:"inclusion",                   category: "Search Methods (Itemized)",   method:"Lobbying Registrations"},
                 {name: "Limit",                      parameter:"limit",                    kind:"inclusion",                   category: "Politicians (Aggregate)",     method: "Top Politicians by Contributions Received"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Politicians by Contributions Received"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Contributors"},
                 {name: "Limit",                      parameter:"limit",                    kind:"inclusion",                   category: "Politicians (Aggregate)",     method: "Top Contributors"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Contributors"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Industries"},
                 {name: "Limit",                      parameter:"limit",                    kind:"inclusion",                   category: "Politicians (Aggregate)",     method: "Top Industries"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Industries"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Unknown Industries"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Unknown Industries"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Sectors"},
                 {name: "Limit",                      parameter:"limit",                    kind:"inclusion",                   category: "Politicians (Aggregate)",     method: "Top Sectors"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Top Sectors"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Local Breakdown"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Local Breakdown"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "Contributor Type Breakdown"},
                 {name: "Cycle",                      parameter:"cycle",                    kind:"string",                      category: "Politicians (Aggregate)",     method: "Contributor Type Breakdown"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "FEC Summary"},
                 {name: "Entity ID",                  parameter:"entity_id",                kind:"string",                      category: "Politicians (Aggregate)",     method: "FEC Independent Expenditures"},

                 ]

search_params.each do |p|
  parameter_hash = {name: p[:name], parameter: p[:parameter], kind: p[:kind], category: p[:category], method: p[:method]}
  SearchParameter.create(parameter_hash)
end

